### PR TITLE
Replaced class diagram with an updated one

### PR DESCRIPTION
**Pull request by aneesh404**

### CODE REVIEW

**Comment by gabrielefronze** [comment]
The class diagram is not up to date and does not represent the real state of the code. Please edit this one accordingly! Thanks

**Comment by leggerf** [comment]
@iH8c0ff33 may I assign this to you?

**Comment by iH8c0ff33** [comment]
I can create a new diagram, but a new PR must be opened since the source branch cannot be modified.

**Comment by leggerf** [comment]
ok, closing

**Pull request closed without merging**
