### PR TITLE
Adding fixes to blender benchmark's get-settings method

### PR DESCRIPTION
**Pull request by aneesh404**
This PR amends the function ```get-settings``` by removing the previous interfacing based function to printing the available settings in a benchmark.

This aims to solve point#2 in #42

### CODE REVIEW

**Comment by leggerf** [comment]
looks good Aneesh, can you also pls update the documentation (User guide)?

**Comment by leggerf** [comment]
would also be good to have an option like:

 python3 user_interfaces/cli.py get-settings -b blender_benchmark -s settings1.json

that outputs 
cat benchmarks/blender_benchmark/settings/settings1.json
{
    "blender_version":"2.92" ,
    "scenes": ["bmw27"],
    "device_type":"CUDA",
    "verbosity":"3"
}

**Comment by aneesh404** [comment]
Hi @leggerf , the above functionality has been incorporated as well in the commit: 9472eb0

**Comment by leggerf** [comment]
@aneesh404 get-settings work for blender, but not for dummy benchmark, see below:

legger@laptop-fede:~/OpenForBC-Benchmark$ python3 user_interfaces/cli.py get-settings -b blender_benchmark
settings1.json
settings2.json
legger@laptop-fede:~/OpenForBC-Benchmark$ python3 user_interfaces/cli.py get-settings -b dummy_benchmark
Traceback (most recent call last):
  File "user_interfaces/cli.py", line 292, in <module>
    app()
  File "/home/legger/.local/lib/python3.6/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/home/legger/.local/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/legger/.local/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/legger/.local/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/legger/.local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/legger/.local/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/legger/.local/lib/python3.6/site-packages/typer/main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "user_interfaces/cli.py", line 287, in get_settings
    for setting in output:
TypeError: 'NoneType' object is not iterable

**Comment by aneesh404** [comment]
Hi, sorry my bad. I didn't test that command with dummy_benchmark. It should be fixed now.

**Pull request merged**
