### PR TITLE
Clean up cpp matmul benchmark

### PR DESCRIPTION
**Pull request by iH8c0ff33**
- Fix clang-tidy warnings
- Format code according to defined `.clang-format`

### CODE REVIEW

**Review by leggerf — COMMENTED** [review]
Aren't there even more (but obviously different) warnings than before?

**Comment by iH8c0ff33** [comment]
No, actually less warnings now... But the ones we're seeing now are disabled (cppcoreguidelines) in our .clang-tidy configuration file, but the action doesn't use it. I'm going to check if there's a way to make it use the configuration or search for a newer GitHub action which does what we want.

**Comment by iH8c0ff33** [comment]
The CI action's [documentation](https://github.com/shenxianpeng/cpp-linter-action#tidy-checks) shows that if no checks are specified in the action inputs, the default is to enable all these: `boost-*,bugprone-*,performance-*,readability-*,portability-*,modernize-*,clang-analyzer-*,cppcoreguidelines-*`.
The value of the `tidy-checks` input is *appended* to the checks specified in the `.clang-tidy` configuration file. Setting `tidy-checks` to an empty string should enable only the checks we specify in the configuration file, I'll open a PR for that.

**Comment by leggerf** [comment]
thanks, then I'll merge this one

**Pull request merged**
