### PR TITLE
Documentation for log functionality in UI.

### PR DESCRIPTION
**Pull request by aneesh404**
This PR tries to solve #67

### CODE REVIEW

**Comment by leggerf** [comment]
I looked in the blender [implementation.py](https://github.com/Open-ForBC/OpenForBC-Benchmark/blob/devel/benchmarks/blender_benchmark/implementation.py), and I completely failed to find how to do this:

To properly propagate the execution logs, return the logs as a dictionary with the format ```{"output":<logging data>}``` from the method responsible for running the benchmark, ie. ```startBenchmark()``` in usual cases.

Can you pls link to the line in the code where this should be done?

**Review by leggerf — CHANGES_REQUESTED** [review]
see comment

**Comment by aneesh404** [comment]
The mentioned format is used. Essentially It's a format that unifies => making the logging consistent.
https://github.com/Open-ForBC/OpenForBC-Benchmark/blob/3a98f4f649ade2eb35c5f82bb1a6b7a7016c5ed1/benchmarks/blender_benchmark/implementation.py#L94

**Comment by leggerf** [comment]
ok, I think the confusion came from me looking at implementation.py without the logging implementation...
        for spec in specs:
            returnDict[spec] = s.get(spec, None)
        return returnDict

**Pull request merged**
