### PR TITLE
Fixing various issues with TS, MNIST and CIFAR

### PR DESCRIPTION
**Pull request by gabrielefronze**
Fixes requirements files.

Defines test preset (able to run on CPU).

Defines the `test_preset` to call the right preset.

### CODE REVIEW

**Comment by gabrielefronze** [comment]
@leggerf feel free to merge: the failures are merely due to the metrics definition being GPU-oriented.

**Comment by gabrielefronze** [comment]
> The `test_preset` should return dummy stats.
> 
> In GPU based benchmarks it should not fall back to CPU, it shouldn't do any computation.
> 
> If we don't want to use the `test_preset` we should just make it optional (as it is currently) and not run any preset when testing the benchmark.

Since the lack of testing made the benchmarks unable to run, I guess we should provide a test profile.
Right now it works and allows us to test the benchmarks with low effort.
Should I return dummy stats to let it complete?

**Comment by iH8c0ff33** [comment]
That, or we allow definition of preset-dependent stats, but it could complicate the benchmark definition process.

**Comment by gabrielefronze** [comment]
Right! I've added a dummy stats return and now tests are working right.
Merging.

**Pull request merged**
